### ISSUE TITLE
求助：mac 下无法启动，然后报错

### ISSUE THREAD

**Issue by dear-lizhihua** [iview/iview#1583]
mac 下无法启动，然后报错

```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run dev --scripts-prepend-node-path=auto

> iview@2.0.0 dev /Users/lizhihua/workspace/vue/iview-offical
> webpack-dev-server --content-base test/ --open --inline --hot --compress --history-api-fallback --port 8081 --config build/webpack.dev.config.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iview@2.0.0 dev: `webpack-dev-server --content-base test/ --open --inline --hot --compress --history-api-fallback --port 8081 --config build/webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iview@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lizhihua/.npm/_logs/2017-08-10T11_24_31_437Z-debug.log
```

/Users/lizhihua/.npm/_logs/2017-08-10T11_24_31_437Z-debug.log 文件如下

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@5.3.0
3 info using node@v6.11.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle iview@2.0.0~predev: iview@2.0.0
6 info lifecycle iview@2.0.0~dev: iview@2.0.0
7 verbose lifecycle iview@2.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle iview@2.0.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/lizhihua/workspace/vue/iview-offical/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/Users/lizhihua/bin
9 verbose lifecycle iview@2.0.0~dev: CWD: /Users/lizhihua/workspace/vue/iview-offical
10 silly lifecycle iview@2.0.0~dev: Args: [ '-c',
10 silly lifecycle   'webpack-dev-server --content-base test/ --open --inline --hot --compress --history-api-fallback --port 8081 --config build/webpack.dev.config.js' ]
11 silly lifecycle iview@2.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle iview@2.0.0~dev: Failed to exec dev script
13 verbose stack Error: iview@2.0.0 dev: `webpack-dev-server --content-base test/ --open --inline --hot --compress --history-api-fallback --port 8081 --config build/webpack.dev.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid iview@2.0.0
15 verbose cwd /Users/lizhihua/workspace/vue/iview-offical
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "dev" "--scripts-prepend-node-path=auto"
18 verbose node v6.11.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error iview@2.0.0 dev: `webpack-dev-server --content-base test/ --open --inline --hot --compress --history-api-fallback --port 8081 --config build/webpack.dev.config.js`
22 error Exit status 1
23 error Failed at the iview@2.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dear-lizhihua** [comment]
搜了下，得在 host 加 127.0.0.1 localhost。
http://blog.leanote.com/post/freemem/%E8%A7%A3%E5%86%B3node%E8%BF%90%E8%A1%8C%E6%97%B6getaddrinfo-ENOTFOUND-localhost%E9%94%99%E8%AF%AF
