### ISSUE TITLE
Trying to build iView with NuxtJS. But it doesn't allow in pipeline...

### ISSUE THREAD

**Issue by rlam3** [iview/iview#1984]
```bash
ERROR in multi vue vue-router vue-meta vuex iView axis
Module not found: Error: Can't resolve 'iView' in '/opt/atlassian/pipelines/agent/build'
 @ multi vue vue-router vue-meta vuex iView axis
ERROR in ./plugins/iView.js
Module not found: Error: Can't resolve 'iView' in '/opt/atlassian/pipelines/agent/build/plugins'
 @ ./plugins/iView.js 3:0-26
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
Error: Webpack build exited with errors
    at /opt/atlassian/pipelines/agent/build/node_modules/nuxt/lib/builder/builder.js:498:27
    at emitRecords.err (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/opt/atlassian/pipelines/agent/build/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/opt/atlassian/pipelines/agent/build/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:354:15)
    at /opt/atlassian/pipelines/agent/build/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/opt/atlassian/pipelines/agent/build/node_modules/async/dist/async.js:998:13)
    at /opt/atlassian/pipelines/agent/build/node_modules/async/dist/async.js:906:16
    at /opt/atlassian/pipelines/agent/build/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Any Idea why this is happening and how to integrate iView with NuxtJS properly? Thanks!

**Comment by SergioCrisostomo** [comment]
@rlam3 `iView` should be lowercase. Please try with `iview`. 

Closing as dup of https://github.com/iview/iview/issues/1942
