### ISSUE TITLE
[Bug Report]''Maximum call stack size exceeded" when I use IView MenuItem

### ISSUE THREAD

**Issue by Lionad-Morotar** [iview/iview#3900]
### Environment
WIN10 | vue 2.5.16 | iview 2.14.2 | Chrome/65.0.3325.181 YaBrowser/18.4.1.871 Yowser/2.5

### Reproduction link
[https://github.com/Lionad-Morotar/NightLaw/tree/develop](https://github.com/Lionad-Morotar/NightLaw/tree/develop)

### Steps to reproduce
任意一个组件中, 如src/page/home/home.vue 只要使用MenuItem, Node就会报栈溢出错误;
错误信息如下:
```
[Vue warn]: Error in data(): "RangeError: Maximum call stack size exceeded"

found in

---> <MenuGroup>
       <Menu>
         <HOMELEFT> at src\pages\home\Left.vue
           <ICol>
             <Row>
               <APP> at src\App.vue

                 <Root>
TIME : Sat Jun 16 2018 19:03:59 GMT 0800 (中国标准时间) ||| URL : /index
error during render : /index
RangeError: Maximum call stack size exceeded
    at mergeData (D:\@github\NightLaw\node_modules\vue\dist\vue.runtime.common.js:1126:20)
    at mergeData (D:\@github\NightLaw\node_modules\vue\dist\vue.runtime.common.js:1137:7)
    at mergeData (D:\@github\NightLaw\node_modules\vue\dist\vue.runtime.common.js:1137:7)
    at mergeData (D:\@github\NightLaw\node_modules\vue\dist\vue.runtime.common.js:1137:7)
```

### What is expected?
正常运行

### What is actually happening?
栈溢出错误

---
错误中有 vue.runtime.common.js 信息, 尝试过在项目 webpack.base.js 将引入 vue 文件转为 vue/dist./vue.js , 无效;

![image](https://user-images.githubusercontent.com/26913795/41498225-a12d1abc-719a-11e8-84bd-64b18f57d46f.png)

**Comment by Lionad-Morotar** [comment]
NavMenu组件找不到合适的替代品, 项目暂时回退到刀耕火种时代...

**Comment by weoil** [comment]
遇到一样的问题 后来发现是Vue.mixin注册函数的事情，删掉之后好了

**Comment by wilsonIs** [comment]
@Lionad-Morotar 遇到同样的问题，
@weoil 请问有发现是什么原因么？

**Comment by weoil** [comment]
把 Item或者sub里mixin的data中的menu直接赋值null的话运行是正常的，应该是一直重复调用有关这个属性的生命周期函数然后就爆了。我的问题是在客户端入口里加了一个自己的全局mixin，应该是有了什么冲突才这样的，删掉自己定义的那个就好了。 @wilsonIs

**Comment by wilsonIs** [comment]
我可能是其它的原因，跟mixin没有关系
我是spa/ssr页面，刚打开页面时没问题，刷新页面才会出现下面这个错误
@weoil 

![image](https://user-images.githubusercontent.com/22462100/43045442-56d2b464-8deb-11e8-837d-01e48621a422.png)

**Comment by weoil** [comment]
@wilsonIs 可以发一份代码给我吗  我的也是首屏没问题 刷新出现  weoil@live.cn

**Comment by wilsonIs** [comment]
@weoil 不好意思，内部代码不能拷贝。
用的egg-view-vue-ssr，还没找到排查问题的思路，等找到了我回来说。。

**Comment by weoil** [comment]
@wilsonIs  我觉得如果出现这个问题 一定是出现在main.js和client.js这两个文件里 祝好

**Comment by Lamborshea** [comment]
同遇相同问题，
```
[Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded"
```
排除出来是 Layout 标签和 Menu 标签一起发生的错误

**Comment by Lionad-Morotar** [comment]
@wilsonIs @weoil QAQ 我正好相反啊 首屏有问题, 热更新没问题 ...

**Comment by Lionad-Morotar** [comment]
经过这次BUG打击, 我怕是由三维成为平面的了, 发现刀耕火种HTML+CSS真好用.

**Comment by SergeyMiracle** [comment]
Well not that i don't like chines, but i can not understand it. Can some one explain how to work around this bug???

**Comment by linwenfeng122** [comment]
我在组件内使用layout这个组件就会报溢出

**Comment by hellozhangran** [comment]
遇到同样的问题，确实去掉Vue.mixin就好了，但项目需要全局注册一个计算属性，无法去掉Vue.mixin。
