### ISSUE TITLE
 iview.js?5654:5944 Uncaught TypeError: value.getTime is not a function

### ISSUE THREAD

**Issue by denghp** [iview/iview#794]
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

```
<Form-item label="选择日期">
                                    <Row>
                                        <Col span="11">
                                        <Form-item prop="createTime">
                                            <Date-picker type="date" placeholder="选择日期" v-model="userInfo.createTime"></Date-picker>
                                        </Form-item>
                                        </Col>
                                    </Row>
                                </Form-item>

```

```
ruleValidate: {
          createTime: [
            { required: true, type: 'date', message: '请选择日期', trigger: 'change' }
          ]
        }
```

```
methods: {
      mockUserData () {
        let uid = this.$route.query.id
        this.$Loading.start()
        getUserInfo(uid).then((res) => {
          this.$Loading.finish()
          this.userInfo = res.data.data
        })
      },
      handleSubmit (name) {
        this.$refs[name].validate((valid) => {
          if (valid) {
            this.$Message.success('提交成功!')
          } else {
            this.$Message.error('表单验证失败!')
          }
        })
      }
    }
```

点击提交按钮验证，报如下异常：

### 问题现象，以及你期望的结果是怎样的?
```
Uncaught TypeError: value.getTime is not a function
    at Object.date [as validator] (eval at <anonymous> (http://localhost:8080/app.js:7950:2), <anonymous>:5944:45)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:7950:2), <anonymous>:5412:12)
    at next (eval at <anonymous> (http://localhost:8080/app.js:7950:2), <anonymous>:586:7)
    at asyncSerialArray (eval at <anonymous> (http://localhost:8080/app.js:7950:2), <anonymous>:592:3)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:7950:2), <anonymous>:626:7)
    at Array.forEach (native)
    at asyncMap (eval at <anonymous> (http://localhost:8080/app.js:7950:2), <anonymous>:623:14)
    at Schema.validate (eval at <anonymous> (http://localhost:8080/app.js:7950:2), <anonymous>:5339:24)
    at VueComponent.validate (eval at <anonymous> (http://localhost:8080/app.js:7950:2), <anonymous>:11032:23)
    at VueComponent.boundFn [as validate] (eval at <anonymous> (http://localhost:8080/app.js:612:2), <anonymous>:129:14)
```

**Comment by icarusion** [comment]
provide online code
