### ISSUE TITLE
TypeError: value.getTime is not a function

### ISSUE THREAD

**Issue by denghp** [iview/iview#803]
### iView 版本号
2.0.0-rc.11

### 操作系统/浏览器 版本号
 macOS/Chrome 56 

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

我是拷贝的https://www.iviewui.com/components/form 验证这段的代码使用的

```
<template>
    <Form ref="formValidate" :model="formValidate" :rules="ruleValidate" :label-width="80">
        <Form-item label="姓名" prop="name">
            <Input v-model="formValidate.name" placeholder="请输入姓名"></Input>
        </Form-item>
        <Form-item label="邮箱" prop="mail">
            <Input v-model="formValidate.mail" placeholder="请输入邮箱"></Input>
        </Form-item>
        <Form-item label="城市" prop="city">
            <Select v-model="formValidate.city" placeholder="请选择所在地">
                <Option value="beijing">北京市</Option>
                <Option value="shanghai">上海市</Option>
                <Option value="shenzhen">深圳市</Option>
            </Select>
        </Form-item>
        <Form-item label="选择日期">
            <Row>
                <Col span="11">
                <Form-item prop="date">
                    <Date-picker type="date" placeholder="选择日期" v-model="formValidate.date"></Date-picker>
                </Form-item>
                </Col>
                <Col span="2" style="text-align: center">-</Col>
                <Col span="11">
                <Form-item prop="time">
                    <Time-picker type="time" placeholder="选择时间" v-model="formValidate.time"></Time-picker>
                </Form-item>
                </Col>
            </Row>
        </Form-item>
        <Form-item label="性别" prop="gender">
            <Radio-group v-model="formValidate.gender">
                <Radio label="male">男</Radio>
                <Radio label="female">女</Radio>
            </Radio-group>
        </Form-item>
        <Form-item label="爱好" prop="interest">
            <Checkbox-group v-model="formValidate.interest">
                <Checkbox label="吃饭"></Checkbox>
                <Checkbox label="睡觉"></Checkbox>
                <Checkbox label="跑步"></Checkbox>
                <Checkbox label="看电影"></Checkbox>
            </Checkbox-group>
        </Form-item>
        <Form-item label="介绍" prop="desc">
            <Input v-model="formValidate.desc" type="textarea" :autosize="{minRows: 2,maxRows: 5}" placeholder="请输入..."></Input>
        </Form-item>
        <Form-item>
            <Button type="primary" @click="handleSubmit('formValidate')">提交</Button>
            <Button type="ghost" @click="handleReset('formValidate')" style="margin-left: 8px">重置</Button>
        </Form-item>
    </Form>
</template>
<script>
    export default {
        data () {
            return {
                formValidate: {
                    name: '',
                    mail: '',
                    city: '',
                    gender: '',
                    interest: [],
                    date: '2016-12-20', // 给date赋值就报错
                    time: '',
                    desc: ''
                },
                ruleValidate: {
                    name: [
                        { required: true, message: '姓名不能为空', trigger: 'blur' }
                    ],
                    mail: [
                        { required: true, message: '邮箱不能为空', trigger: 'blur' },
                        { type: 'email', message: '邮箱格式不正确', trigger: 'blur' }
                    ],
                    city: [
                        { required: true, message: '请选择城市', trigger: 'change' }
                    ],
                    gender: [
                        { required: true, message: '请选择性别', trigger: 'change' }
                    ],
                    interest: [
                        { required: true, type: 'array', min: 1, message: '至少选择一个爱好', trigger: 'change' },
                        { type: 'array', max: 2, message: '最多选择两个爱好', trigger: 'change' }
                    ],
                    date: [
                        { required: true, type: 'date', message: '请选择日期', trigger: 'change' }
                    ],
                    time: [
                        { required: true, type: 'date', message: '请选择时间', trigger: 'change' }
                    ],
                    desc: [
                        { required: true, message: '请输入个人介绍', trigger: 'blur' },
                        { type: 'string', min: 20, message: '介绍不能少于20字', trigger: 'blur' }
                    ]
                }
            }
        },
        methods: {
            handleSubmit (name) {
                this.$refs[name].validate((valid) => {
                    if (valid) {
                        this.$Message.success('提交成功!');
                    } else {
                        this.$Message.error('表单验证失败!');
                    }
                })
            },
            handleReset (name) {
                this.$refs[name].resetFields();
            }
        }
    }
</script>
```
### 问题现象，以及你期望的结果是怎样的?
验证date类型是否为空时，如果date初始化为空值，则正常，但是设置了值之后就报如下异常
```
Uncaught TypeError: value.getTime is not a function
    at Object.date [as validator] (http://localhost:8081/dist/vendors.js:13604:281)
    at http://localhost:8081/dist/vendors.js:13530:929
    at next (http://localhost:8081/dist/vendors.js:13001:1569)
    at asyncSerialArray (http://localhost:8081/dist/vendors.js:13001:1615)
    at http://localhost:8081/dist/vendors.js:13001:2303
    at Array.forEach (native)
    at asyncMap (http://localhost:8081/dist/vendors.js:13001:2227)
    at Schema.validate (http://localhost:8081/dist/vendors.js:13527:2357)
    at VueComponent.validate (http://localhost:8081/dist/vendors.js:13688:90409)
    at VueComponent.boundFn [as validate] (http://localhost:8081/dist/vendors.js:2564:14)
```

**Comment by icarusion** [comment]
provide online code

**Comment by qinghua5453** [comment]
同问，我也遇到同样的问题，在第一次post的时候 如果选择了日期还ok，第二次进来默认是能渲染日期的，但如果不重新点击下，就会出现如上报错。
