### ISSUE TITLE
【BUG】按需引用若干问题

### ISSUE THREAD

**Issue by yuqigong** [iview/iview#879]
```javascript
import { Row, Col } from 'iview/src/components/grid/col.vue';
import Menu from 'iview/src/components/menu/menu.vue';
import Submenu from 'iview/src/components/menu/submenu.vue';
import MenuItem from 'iview/src/components/menu/menu-item.vue';
import Breadcrumb from 'iview/src/components/breadcrumb';
import BreadcrumbItem from 'iview/src/components/breadcrumb/breadcrumb-item.vue';
import Dropdown from 'iview/src/components/dropdown';
import DropdownMenu from 'iview/src/components/dropdown/dropdown-menu.vue';
import DropdownItem from 'iview/src/components/dropdown/dropdown-item.vue';
Vue.component(Col.name, Col);
Vue.component(Menu.name, Menu);
Vue.component(Submenu.name, Submenu);
Vue.component(MenuItem.name, MenuItem);
Vue.component(Breadcrumb.name, Breadcrumb);
Vue.component(BreadcrumbItem.name, BreadcrumbItem);
Vue.component(Dropdown.name, Dropdown);
Vue.component(Dropdown.name, DropdownMenu);
Vue.component(Dropdown.name, DropdownItem);
```
以上引用方式，均无法正确使用组件。

- `Col` 组件样式有问题。`ivu-col` 所属样式都没有生效。
- `Dropdown` 子组件`DropdownMenu`报错。

   ```javascript
   Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (eval at <anonymous> (http://localhost:8080/bundle.js:807:1), <anonymous>:87:38)
    at Object.isReservedTag (eval at <anonymous> (http://localhost:8080/bundle.js:807:1), <anonymous>:4544:28)
    at Function.Vue.(anonymous function) [as component] (eval at <anonymous> (http://localhost:8080/bundle.js:807:1), <anonymous>:4215:46)
    at eval (eval at <anonymous> (http://localhost:8080/bundle.js:1006:1), <anonymous>:40:15)
    at Object.<anonymous> (http://localhost:8080/bundle.js:1006:1)
    at __webpack_require__ (http://localhost:8080/bundle.js:658:30)
    at fn (http://localhost:8080/bundle.js:86:20)
    at Object.<anonymous> (http://localhost:8080/bundle.js:1469:18)
    at __webpack_require__ (http://localhost:8080/bundle.js:658:30)
    at http://localhost:8080/bundle.js:707:39
   ```
- `Menu | Breadcrumb` 子组件需要指定具体路径，否则报错；希望可以改为直接引用父级；

补充，可以用这个方式引用，**但仍旧存在以上问题**：

```javascript
import {
    Row,
    Col,
    Menu,
    Submenu,
    MenuItem,
    Icon,
    Breadcrumb,
    BreadcrumbItem,
    Button,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Input
} from 'iview';
Vue.component(Row.name, Row);
Vue.component(Col.name, Col);
Vue.component(Menu.name, Menu);
Vue.component(Submenu.name, Submenu);
Vue.component(MenuItem.name, MenuItem);
Vue.component(Icon.name, Icon);
Vue.component(Breadcrumb.name, Breadcrumb);
Vue.component(BreadcrumbItem.name, BreadcrumbItem);
Vue.component(Button.name, Button);
Vue.component(Dropdown.name, Dropdown);
Vue.component(DropdownMenu.name, DropdownMenu);
Vue.component(DropdownItem.name, DropdownItem);
Vue.component(Input.name, Input);
```

### iView 版本号
2.0.0-rc.12

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.3.0

### 复现步骤
必现

### 问题现象，以及你期望的结果是怎样的?
组件无法按需引用，希望可以类似以下引用方式：

```javascript
import Vue from 'vue'
import { Button, Select } from 'iview'
import App from './App.vue'

Vue.component(Button.name, Button)
Vue.component(Select.name, Select)
/* 或写为
 * Vue.use(Button)
 * Vue.use(Select)
 */

new Vue({
  el: '#app',
  render: h => h(App)
})
```

### 你估计可能的原因是什么（选填）？
组件约定有问题

**Comment by woshiguabi** [comment]
因为在源码中 `dropdownMenu` 没有 `name` 属性。
```
// iview/src/components/dropdown/dropdown-menu.vue

<template>
    <ul class="ivu-dropdown-menu"><slot></slot></ul>
</template>
<script>
    export default {};
</script>
```

尽量不要依赖于组件的name属性，按需引用最好自己输入name。
另外，也尽量不要直接引用组件目录下的vue文件，应该引用`index.js`文件。
```
import Dropdown form 'iview/src/conponenets/dropdown'
Vue.conponent('Dropdown', Dropdown);
Vue.conponent('Dropdown-item', Dropdown.Item);
Vue.conponent('Dropdown-menu', Dropdown.Menu);
```

**Comment by yuqigong** [comment]
感谢回复。
还在学习中，通过之前使用的情况和上述分析的原因来看，iview 组件单独引用可能遇到的问题会比较多。目前改为全部加载。

**Comment by PeiXueYang** [comment]
同样的 问题 按需 引入 DatePicker 报错。
